//! Desktop unlock code — public, deterministic, server-free.
//!
//! Rust twin of `web/src/lib/desktopCode.ts`. The two MUST agree byte for byte:
//! the website shows the code, this crate verifies it. Both sides carry the same
//! hard-coded test vectors, so a silent drift fails `cargo test`.
//!
//! Contract:
//!   HOUR_MS = 3_600_000
//!   bucket  = floor(now_ms / HOUR_MS)          (UTC epoch hour index)
//!   payload = "nft1:{slug}:{bucket}"           (ASCII)
//!   digest  = SHA-256(payload)                 (32 bytes)
//!   value   = big-endian uint40 from digest[0..5]
//!   chars   = 8 × base32(value), MSB first
//!   code    = "XXXX-XXXX"
//!
//! The project is open source, so this is a rotating convenience gate that
//! brings people back to the site — not a security boundary. Nothing here is
//! secret and nothing here needs to be secret.

use sha2::{Digest, Sha256};

pub const CODE_VERSION: &str = "nft1";
pub const HOUR_MS: i64 = 3_600_000;

/// Crockford-style alphabet: no I, O, 0, 1. Exactly 32 bytes.
const BASE32: &[u8; 32] = b"ABCDEFGHJKLMNPQRSTUVWXYZ23456789";

/// Index of the UTC hour bucket `now_ms` falls in.
pub fn bucket_index(now_ms: i64) -> i64 {
    now_ms.div_euclid(HOUR_MS)
}

pub fn bucket_start_ms(bucket: i64) -> i64 {
    bucket * HOUR_MS
}

/// Exclusive: the code dies exactly at this instant.
pub fn bucket_end_ms(bucket: i64) -> i64 {
    bucket_start_ms(bucket) + HOUR_MS
}

/// Uppercase and drop separators, so "abcd-efgh" and "ABCDEFGH" match.
pub fn normalize_code(raw: &str) -> String {
    raw.trim()
        .to_uppercase()
        .chars()
        .filter(|c| c.is_ascii_alphanumeric())
        .collect()
}

fn to_base32_chars(digest: &[u8]) -> String {
    let n: u64 = (digest[0] as u64) << 32
        | (digest[1] as u64) << 24
        | (digest[2] as u64) << 16
        | (digest[3] as u64) << 8
        | (digest[4] as u64);
    let mut chars: Vec<u8> = Vec::with_capacity(8);
    let mut v = n;
    for _ in 0..8 {
        chars.push(BASE32[(v % 32) as usize]);
        v /= 32;
    }
    chars.reverse();
    String::from_utf8(chars).expect("base32 alphabet is ASCII")
}

fn format_code(raw8: String) -> String {
    let c: Vec<char> = raw8.chars().collect();
    format!(
        "{}{}{}{}-{}{}{}{}",
        c[0], c[1], c[2], c[3], c[4], c[5], c[6], c[7]
    )
}

/// The code for `slug` in hour bucket `bucket`.
pub fn code_for_bucket(slug: &str, bucket: i64) -> String {
    let payload = format!("{}:{}:{}", CODE_VERSION, slug, bucket);
    let digest = Sha256::digest(payload.as_bytes());
    format_code(to_base32_chars(&digest))
}

/// Returns `Some(expires_at)` when `code` unlocks `slug` at `now_ms`.
/// Only the current hour bucket is accepted — there is no grace window, so a
/// code is always at most one hour old.
pub fn verify_code(slug: &str, code: &str, now_ms: i64) -> Option<i64> {
    let bucket = bucket_index(now_ms);
    let expected = code_for_bucket(slug, bucket);
    if normalize_code(code) == normalize_code(&expected) {
        Some(bucket_end_ms(bucket))
    } else {
        None
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Generated by the TypeScript implementation (`web/src/lib/desktopCode.ts`)
    /// — these are the cross-language contract. Regenerate with:
    ///   node --experimental-strip-types .workbuddy/tmp/gen-code-vectors.mjs
    const VECTORS: [(&str, i64, &str); 8] = [
        ("raw-to-iso", 0, "Y5JM-D2RD"),
        ("raw-to-iso", 1, "AEN5-7BJ8"),
        ("kfx-to-epub", 497_100, "QX26-3C7S"),
        ("kfx-to-epub", 497_101, "AAWX-EWSM"),
        ("step-to-stl", 497_100, "532H-MDMS"),
        ("wad-extractor", 497_100, "98BP-GVLQ"),
        ("pfm-to-ttf", 1_000_000, "M5BF-J4AV"),
        ("mts-to-mp4", 2_147_483_647, "88VC-587A"),
    ];

    #[test]
    fn matches_the_typescript_implementation() {
        for (slug, bucket, expected) in VECTORS {
            assert_eq!(
                code_for_bucket(slug, bucket),
                expected,
                "vector drift for `{slug}` @ bucket {bucket}"
            );
        }
    }

    #[test]
    fn codes_are_per_tool() {
        let a = code_for_bucket("kfx-to-epub", 497_100);
        let b = code_for_bucket("wad-extractor", 497_100);
        assert_ne!(a, b, "different tools must not share a code");
    }

    #[test]
    fn codes_rotate_every_hour() {
        let a = code_for_bucket("raw-to-iso", 500);
        let b = code_for_bucket("raw-to-iso", 501);
        assert_ne!(a, b);
        // Same bucket always yields the same code (deterministic, no server).
        assert_eq!(a, code_for_bucket("raw-to-iso", 500));
    }

    #[test]
    fn normalize_accepts_lowercase_and_spacing() {
        let code = code_for_bucket("raw-to-iso", 500);
        assert_eq!(normalize_code(&code.to_lowercase()), normalize_code(&code));
        assert_eq!(normalize_code(&format!(" {code} ")), normalize_code(&code));
        assert_eq!(
            normalize_code(&code.replace('-', " ")),
            normalize_code(&code)
        );
    }

    #[test]
    fn verify_accepts_the_current_bucket() {
        let bucket = 497_100;
        let now = bucket_start_ms(bucket) + 1_000;
        let code = code_for_bucket("kfx-to-epub", bucket);
        assert_eq!(
            verify_code("kfx-to-epub", &code, now),
            Some(bucket_end_ms(bucket))
        );
    }

    #[test]
    fn verify_rejects_a_stale_bucket() {
        // A code from an hour ago must not unlock anything.
        let old = code_for_bucket("kfx-to-epub", 497_100);
        let now = bucket_start_ms(497_101) + 1_000;
        assert_eq!(verify_code("kfx-to-epub", &old, now), None);
    }

    #[test]
    fn verify_rejects_another_tools_code() {
        let now = bucket_start_ms(497_100) + 1_000;
        let other = code_for_bucket("wad-extractor", 497_100);
        assert_eq!(verify_code("kfx-to-epub", &other, now), None);
    }

    #[test]
    fn expiry_is_never_more_than_one_hour_away() {
        let bucket = 497_100;
        // One millisecond before the boundary: a full hour is still granted at
        // the start of a bucket, and almost none at its very end.
        let start = bucket_start_ms(bucket);
        let expires = verify_code("kfx-to-epub", &code_for_bucket("kfx-to-epub", bucket), start)
            .expect("fresh code must verify");
        assert_eq!(expires - start, HOUR_MS);
        assert!(expires - (start + HOUR_MS - 1) <= HOUR_MS);
    }

    #[test]
    fn bucket_math_is_monotonic_and_aligned() {
        assert_eq!(bucket_index(0), 0);
        assert_eq!(bucket_index(HOUR_MS - 1), 0);
        assert_eq!(bucket_index(HOUR_MS), 1);
        // div_euclid (not `/`) keeps negative timestamps well-defined.
        assert_eq!(bucket_index(-1), -1);
        assert_eq!(bucket_end_ms(0), HOUR_MS);
    }
}
