// AUTO-GENERATED by scripts/gen-mock-tools.mjs — do not edit by hand.
// Source of truth: src-tauri/tools.json. Regenerate with `npm run sync:tools`.
import type { ToolMeta } from "./tauri";

/// Snapshot of the desktop tool manifest. Only used when the UI runs in a plain
/// browser (no Tauri IPC) so the layout can be previewed; the native window
/// always reads the live manifest through `list_tools`.
export const MOCK_TOOLS: ToolMeta[] = [
  {"slug":"raw-to-iso","name":"RAW to ISO","class":"C","engines":["rust-native"],"source":[".raw",".img"],"target":".iso","output_kind":"file","guide":null,"category":"archive","web_slug":null},
  {"slug":"raw-to-wav","name":"RAW to WAV","class":"A","engines":["rust-native"],"source":[".raw"],"target":".wav","output_kind":"file","guide":"Headerless PCM: optional params sample_rate / bits / channels (default 44100/16/1)","category":"audio","web_slug":null},
  {"slug":"eot-to-ttf","name":"EOT to TTF","class":"A","engines":["rust-native"],"source":[".eot"],"target":".ttf","output_kind":"file","guide":null,"category":"font","web_slug":null},
  {"slug":"glb-to-gltf","name":"GLB to GLTF","class":"A","engines":["rust-native"],"source":[".glb"],"target":".gltf","output_kind":"file","guide":null,"category":"3d","web_slug":null},
  {"slug":"exr-to-png","name":"EXR to PNG","class":"A","engines":["rust-native"],"source":[".exr"],"target":".png","output_kind":"file","guide":"HDR float mapped to 8-bit (preview only)","category":"image","web_slug":null},
  {"slug":"opf-to-epub","name":"OPF to EPUB","class":"A","engines":["rust-native"],"source":[".opf"],"target":".epub","output_kind":"file","guide":null,"category":"ebook","web_slug":null},
  {"slug":"sav-to-csv","name":"SAV to CSV","class":"A","engines":["python-fonttools"],"source":[".sav"],"target":".csv","output_kind":"file","guide":"Requires Python + pandas: pip install pandas","category":"data","web_slug":null},
  {"slug":"wad-extractor","name":"WAD Extractor","class":"C","engines":["rust-native"],"source":[".wad"],"target":".wad","output_kind":"dir","guide":"Unpack all lumps to output dir (supports IWAD/PWAD/WAD2/WAD3)","category":"game","web_slug":null},
  {"slug":"pvr-to-png","name":"PVR to PNG","class":"A","engines":["rust-native"],"source":[".pvr"],"target":".png","output_kind":"file","guide":"Uncompressed RGBA8888/RGB888/L8 supported; compressed/2-byte layouts await a native decoder","category":"image","web_slug":null},
  {"slug":"gsm-to-wav","name":"GSM to WAV","class":"A","engines":["ffmpeg"],"source":[".gsm"],"target":".wav","output_kind":"file","guide":"Requires FFmpeg","category":"audio","web_slug":null},
  {"slug":"mts-to-mp4","name":"MTS to MP4","class":"B","engines":["ffmpeg"],"source":[".mts",".m2ts"],"target":".mp4","output_kind":"file","guide":"Requires FFmpeg","category":"video","web_slug":null},
  {"slug":"blend-to-glb","name":"BLEND to GLB","class":"B","engines":["blender"],"source":[".blend"],"target":".glb","output_kind":"file","guide":"Requires Blender","category":"3d","web_slug":null},
  {"slug":"kfx-to-epub","name":"KFX to EPUB","class":"A","engines":["calibre"],"source":[".kfx"],"target":".epub","output_kind":"file","guide":"Requires Calibre (ebook-convert)","category":"ebook","web_slug":null},
  {"slug":"step-to-stl","name":"STEP/IGES/BREP to STL","class":"B","engines":["occt"],"source":[".step",".stp",".iges",".igs",".brep"],"target":".stl","output_kind":"file","guide":"For PRT, export STEP from Creo first; requires FreeCAD/OCCT","category":"3d","web_slug":"prt-to-stl"},
  {"slug":"pfm-to-ttf","name":"PFM/PFB to TTF","class":"A","engines":["python-fonttools"],"source":[".pfb",".pfa"],"target":".ttf","output_kind":"file","guide":"Requires Python + fontforge; the .pfm must share the same name and directory","category":"font","web_slug":null},
];
